# Leapcell deployment configuration for F1 Telegram Bot
apiVersion: v1
kind: Service
metadata:
  name: f1-bot-leapcell-test
spec:
  # Port configuration
  ports:
    - port: 8080
      protocol: HTTP
      targetPort: 8080
      name: http

  # Environment variables
  env:
    - name: TELEGRAM_BOT_TOKEN
      value: YOUR_BOT_TOKEN_HERE
    - name: PORT
      value: "8080"
    - name: PYTHON_VERSION
      value: "3.11.0"
    - name: WORKER_CLASS
      value: "gthread"
    - name: WORKERS
      value: "1"
    - name: THREADS
      value: "4"
    - name: TIMEOUT
      value: "120"
    - name: MAX_REQUESTS
      value: "1000"
    - name: MAX_REQUESTS_JITTER
      value: "100"
    - name: GUNICORN_CMD_ARGS
      value: "--bind :8080 --workers 1 --worker-class gthread --threads 4 --timeout 120 --keep-alive 5 --max-requests 1000 --max-requests-jitter 100"
    - name: ENABLE_CLAUDE_HAIKU
      value: "4.5"

  # Docker configuration
  image:
    repository: f1-bot-leapcell
    tag: latest
    build:
      dockerfile: Dockerfile
      context: .

  # Health checks
  healthCheck:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  # Readiness probe
  readinessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1

  # Resource limits
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

  # Scaling
  replicas: 1
  # 
  # Autoscaling configuration
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCpuUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # Network policies
  networkPolicy:
    enabled: true
    ingress:
      - port: 8080
        protocol: TCP
    
  # Storage (for user streams and logs)
  volumes:
    - name: app-storage
      persistentVolumeClaim:
        claimName: f1-bot-storage
        size: 1Gi
        storageClass: standard

  # Deployment strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25

  # Additional configuration
  annotations:
    leapcell.io/service-description: "F1 Telegram Bot with live timing, standings, and race information"
    leapcell.io/service-category: "telegram-bot"
    leapcell.io/auto-deploy: "true"
    leapcell.io/build-cache: "true"
    leapcell.io/enable-claude-haiku: "4.5"